services:
  - type: web
    name: backend2
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    pythonVersion: 3.10.3
